# Generated by Django 2.2.3 on 2020-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Country_code', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('WHO_region', models.CharField(max_length=50)),
                ('New_cases', models.IntegerField()),
                ('Cumulative_cases', models.IntegerField()),
                ('New_deaths', models.IntegerField()),
                ('Cumulative_deaths', models.IntegerField()),
            ],
        ),
    ]
