# Generated by Django 2.2.3 on 2020-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Covid19Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Covid19Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('who_region', models.CharField(max_length=50)),
                ('new_cases', models.IntegerField()),
                ('cumulative_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('cumulative_deaths', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='Country_code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='Cumulative_cases',
            new_name='cumulative_cases',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='Cumulative_deaths',
            new_name='cumulative_deaths',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='New_cases',
            new_name='new_cases',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='New_deaths',
            new_name='new_deaths',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='WHO_region',
            new_name='who_region',
        ),
    ]
